### PR TITLE
Added health check for Virtuoso

### LINKED ISSUE #1140: Add virtuoso healthcheck
rootCollections now does not fail but returns empty when Virtuoso is down.  Therefore, we need a new Virtuoso healthcheck to check it directly.

### PR DESCRIPTION
**Pull request by cjmyers**
Closes #1140

### CODE REVIEW

**Comment by jvscholz** [comment]
is this part of the api?

**Comment by cjmyers** [comment]
Yes, once it is approved.  It is a pretty simple one.  It returns HTTP error code 200 when Virtuoso is up and running, and it returns HTTP error code 500 when it is not.

This raises an interesting point.  It would be good to document the reasons for various error codes for each endpoint.  I will log a separate issue.  I would put that at a lower priority though than testing.

**Comment by jvscholz** [comment]
which category does it fall under?

**Comment by cjmyers** [comment]
Probably admin

Chris

**Comment by cjmyers** [comment]
Moved to /admin/virtuoso endpoint

**Pull request merged**
