### PR TITLE
added variables so checkboxes on theme for sbh2 are updated correctly…

### PR DESCRIPTION
**Pull request by danielfang97**
… according to config

### CODE REVIEW

**Comment by cjmyers** [comment]
Seems to be failing testing.  Also, not sure about the logic.  Can you explain it?

**Comment by danielfang97** [comment]
Re ran tests, and now it seems to be passing tests.
I did this because for SBH2, it wasn't passing in the variables to SBH1. So lines 50-52 are adding the variables to theme, so they can be accessed by SBH2. 
For the other changes, I am setting the variable based on whether it's true or false. The issue is that I realized that SBH1 does this differently. I think this would be good to discuss tomorrow.

**Comment by cjmyers** [comment]
Rethink and retest the logic for setting the variables.  Remove tests that are not necessary for getting this to pass.

**Comment by danielfang97** [comment]
Closed, as this PR was replaced with PR #1601

**Pull request closed without merging**
