### PR TITLE
Fix GFF3 issue

### LINKED ISSUE #1492: /gff endpoint does not work properly
When hitting any /gff endpoint (i.e. https://synbiohub.org/public/igem/BBa_B0010/1/gff), it simply returns xml within the .gff file.

### PR DESCRIPTION
**Pull request by cjmyers**
Closes #1492

### CODE REVIEW

**Comment by danielfang97** [comment]
image

Is this correct?

**Comment by cjmyers** [comment]
Nope, GFF3 format defined here:

http://useast.ensembl.org/info/website/upload/gff3.html

**Review by danielfang97 — APPROVED** [review]
It works now

**Comment by danielfang97** [comment]
Can you merge this branch too?

**Pull request merged**
