### PR TITLE
fixes twins for master

### PR DESCRIPTION
**Pull request by jvscholz**

### CODE REVIEW

**Comment by jvscholz** [comment]
seems like twins isn't uploading parts in the way that I expect it to

**Comment by jvscholz** [comment]
this branch's search results have 0 items whereas the other twins branch has items

**Comment by jvscholz** [comment]
updated

**Review by cjmyers — APPROVED** [review]

**Comment by jvscholz** [comment]
looks like it's failing again

**Comment by cjmyers** [comment]
Yes, the fail appears to be on manage.  Namely, you have submitted a 2nd private collection and the order of these collections is not deterministic.  I believe you submitted this 2nd one to test uses.  Probably need to comment out this 2nd collection submission and log another issue about sorting collections on the manage endpoint.

**Pull request merged**
