### PR TITLE
Update version to 1.4.1

### PR DESCRIPTION
**Pull request by cjmyers**

### CODE REVIEW

**Comment by cjmyers** [comment]
@oflatt looks like this broke your tests likely due to my tweak on the footer.  Can you have a look and see what needs to be done to sort this?  Thanks.

**Comment by oflatt** [comment]
It seems to me that you didn't break my tests, but that the test is failing because you changed something. Am I missing something?
You can run bash tests/test.sh --resetpostrequests /setup,
which will save your new version of the response for that endpoint for testing.

**Comment by oflatt** [comment]
Also, make sure to re-build the docker image using the command from the testing README.

**Comment by oflatt** [comment]
Ignore previous comments-
It seems the post request to the setup page really is failing now, and it's failing on my other branches too, giving me the error
+     Error: certificate has expired
+    at TLSSocket.onConnectSecure (_tls_wrap.js:1112:34)
+    at TLSSocket.emit (events.js:182:13)
+    at TLSSocket._finishInit (_tls_wrap.js:625:8)

**Comment by cjmyers** [comment]
Seems this change actually did not break your @oflatt tests after all, so ready for merge once reviewed.

**Pull request merged**
