### PR TITLE
Logout

### PR DESCRIPTION
**Pull request by jvscholz**
Tests endpoint logout

### CODE REVIEW

**Comment by cjmyers** [comment]
You are going to need to rebuild the tests, since the admin registry test needs updating for this and your other pull request:

bash tests/test.sh --stopaftertestsuite --resetalltests 

This is due to a new registry being added to web-of-registries.  We might want to figure out a way to make this test robust to this.

**Comment by cjmyers** [comment]
You are going to need to rebuild the tests, since the admin registry test needs updating for this and your other pull request:

bash tests/test.sh --stopaftertestsuite --resetalltests

This is due to a new registry being added to web-of-registries. We might want to figure out a way to make this test robust to this.

**Comment by jvscholz** [comment]
> You are going to need to rebuild the tests, since the admin registry test needs updating for this and your other pull request:
> 
> bash tests/test.sh --stopaftertestsuite --resetalltests
> 
> This is due to a new registry being added to web-of-registries. We might want to figure out a way to make this test robust to this.

Ok, this should be in the newest pull request, do I have to repush the other branches with these changes?

**Comment by cjmyers** [comment]
You can update those branch once the other is approved.

**Pull request merged**
