### PR TITLE
Test script that creates a new user

### PR DESCRIPTION
**Pull request by oflatt**
This is the first commit for testing- it simply starts a new instance of SynBioHub and creates a new user.

### CODE REVIEW

**Comment by oflatt** [comment]
Another question I have is should the cleanup script be run inside of the test script each time it is run? On one hand, the test.sh script won't work correctly without a cleanup first. On the other, I don't want accidental removal of data.

**Comment by oflatt** [comment]
Looks like it failed to find scripts that it depends on. Do I need to get Travis to recognize them as scripts it needs? Or is the path just wrong?

**Comment by cjmyers** [comment]
Should it be tests/createuser.sh?

**Comment by cjmyers** [comment]
I think in test.sh:

# create a new user
 bash ./createuser.sh

should be:

# create a new user
 bash tests/createuser.sh

maybe, not sure, but it seems it cannot find it.  

Good point about local runs.  Maybe we should have an option on the script on whether you want to cleanup on exit.  However, that being said, if you run the test locally without cleanup, then you might fool yourself it is working when it is not.  Best would be to not have the test image and any local image not conflict with each other.  We should likely discuss how to do this when we meet next.  For now, cleanup on exit is probably fine since for now only travis will run this.

**Comment by zachzundel** [comment]
docker-compose has a -p option which lets you specify the project name,
which is what is prepended to the named volumes and container names. You
could specify a test prefix that will let you isolate all the test env from
development

Zach

**Pull request closed without merging**
