### PR TITLE
Test that data persists after restarting docker containers

### PR DESCRIPTION
**Pull request by oflatt**
The tests create a user in addition to the admin, and uploads three collections. The tests that check the views on these collections are run before and after restarting containers.

### CODE REVIEW

**Comment by oflatt** [comment]
Looks like it's failing due to another date. My last approach to this kind of problem was to add a tag to html that should be ignored, so I'll look into doing something similar.

**Comment by oflatt** [comment]
Looks like not the travis build is also getting the "forEach of undefined" error that I was seeing-
are the docker containers that travis pulls out of date?

**Comment by cjmyers** [comment]
Hmm, should not be.  They get built automatically with pulls to master.

**Comment by cjmyers** [comment]
I wonder if your branch is out-of-date.  Could you try rebasing this branch to master?  You might also see what happens locally when you checkout this branch.

**Comment by oflatt** [comment]
I'll try the rebase. Locally it works correctly.

**Comment by oflatt** [comment]
I ran yarn upgrade and uploaded my local yarn.lock. This seems like the right thing to do unless it updated a dependency it wasn't supposed to.

**Comment by oflatt** [comment]
It seems like it is just the ordering of data in meta.types- not sure how to fix this one yet

**Comment by oflatt** [comment]
Is it possible that the sortByNames function in the lib/views/advancedSearch.js file is going wrong?

**Pull request merged**
