### PR TITLE
Fix problem with editing types

### LINKED ISSUE #1566: Unable to add circular type
When attempting to add circular type, it does not succeed in adding it.

### PR DESCRIPTION
**Pull request by cjmyers**
closes #1566

### CODE REVIEW

**Comment by danielfang97** [comment]
I tried to input in a circular type to a part, but I think I did it wrong, and it threw an error. It can no longer access the part at all. I think when an improper type is added, it should throw an error and try to allow you to change it. Not break the part completely.

**Comment by danielfang97** [comment]
What I'm saying, it should be easier to add/edit a type. People may not know the exact way to do it.

**Comment by cjmyers** [comment]
The inability to access the part after enter a bad type is exactly the error I was trying to fix here.  Could you verify that you tested this on this branch.  I thought I had fixed that behavior.

**Comment by danielfang97** [comment]
Just tested and it appears to no longer throw the error. However, there is a new bug where if you leave the box blank, it remains there. Blank should be treated the same as a wrong type.

**Comment by cjmyers** [comment]
I think that bug was there before too

**Comment by danielfang97** [comment]
So, should I just approve this one? Or are we adding an issue to this PR?

**Review by danielfang97 — APPROVED** [review]
Works as expected. Now, it doesn't throw an error

**Pull request merged**
