### PR TITLE
Responsive buttons

### LINKED ISSUE #1150: Inconsistency with buttons
Some buttons have spelled out names while others are just icons.  We should decide on one format and use that one.

### PR DESCRIPTION
**Pull request by 3ach**
Changes buttons on part pages and the buttons in the top bar to show/hide text based on the window size. 

Closes #1150

### CODE REVIEW

**Comment by cjmyers** [comment]
This looks like it will be very nice.  Thanks.

**Comment by cjmyers** [comment]
BTW: pretty sure you need to regenerate tests for this one.

**Comment by 3ach** [comment]
Please try on your machine before merging, I tested on mine but it will be good to try out on one more!

**Comment by cjmyers** [comment]
Will do

**Comment by cjmyers** [comment]
Made a couple minor changes.  Added tooltips to top icons, and I fixed a wrap with the search bar button.  Otherwise, works great.

**Pull request merged**
