### PR TITLE
Reorganize header layout

### LINKED ISSUE #806: Top right links do not look good with large SBH names and/or small screens
We should perhaps reduce these to icons, so they scale better, or change to some menu that can open.

### PR DESCRIPTION
**Pull request by cjmyers**
Reorganizes header layout to deal with small screens.

Closes #806

### CODE REVIEW

**Comment by cjmyers** [comment]
Not quite ideal yet.  There are three magnifying glasses.  I would like to get rid of the one in the search box, but I don't know how.  Check out the search bar on cnn.com that expands out when clicking on the magnifying glass.  I think this looks pretty cool.  Not sure how to execute it though.

**Comment by cjmyers** [comment]
@oflatt This one changes the top bar quite fundamentally, so it will change the HTML results.  If you let me know how to update these for the test, I can do that for this branch.

**Comment by oflatt** [comment]
@cjmyers , if you look at the README in the tests folder, there is a section called "saving results in order to make tests pass." Ask if anything is unclear.
If you are very sure, you can use the --resetalltests option, but I advise against it. Also, make sure to build the docker image if you haven't.

**Comment by zachzundel** [comment]
Did some more rearranging @cjmyers can you take a look?

**Comment by cjmyers** [comment]
Hmm, cannot see them, I tried checking out issue806 and pulling latest, but I think I'm still snarled:
On branch issue806
Your branch is ahead of 'origin/issue806' by 3 commits.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean

Says I'm ahead by 3 commits, which seems strange.

**Comment by cjmyers** [comment]
I reset, but I still don't see your updates.  Did you push them?

**Comment by cjmyers** [comment]
Thanks.  This is going to be a pretty big one, since it changes the header on every HTML page.

**Comment by zachzundel** [comment]
Yeah.... I would delete your branches locally and re-pull them. The command
is git branch -d <branch name>

**Comment by zachzundel** [comment]
Sorry, I thought I had but they failed. They are pushed now.

**Comment by cjmyers** [comment]
Think it might look better on the right side.  Seems slightly more common to find it there on other cites. 

BTW: noticed this move means search is not on every pages.  We should likely sort that too.  Again, right side would look better I think.

**Comment by zachzundel** [comment]
I think that's fine. How do you feel about removing the URI entirely from
the top bar? It doesn't really mean anything to most users. We could have
the whole thing be search, and have it centered.

Zach

**Comment by udp** [comment]
Massive +1 to this.  The URI is already in the address bar; it doesn't 
need to be repeated in the header.

J

**Comment by zachzundel** [comment]
Moved the search bar again, would appreciate input on this revision. :)

**Comment by cjmyers** [comment]
I think it looks good but a couple minor nits:

1) Can we make the page type on left “inactive” and search bar “active”.  This way your chosen theme color shows up better.
2) Can we add a “<icon?> View” to left of the view pages to be consistent with all the other pages.

Otherwise, I think it looks great!

**Comment by cjmyers** [comment]
Looks pretty good, but there is a small amount of active color showing up below the left inactive part.

screen shot 2019-02-11 at 1 33 15 pm

**Comment by zachzundel** [comment]
Mine looks different... which browser are you using?

[image: image.png]

**Comment by cjmyers** [comment]
It is same for me with both Safari and Chrome.

**Comment by cjmyers** [comment]
Looks good now.  Did you fix it?

**Comment by zachzundel** [comment]
I didn’t do anything.

**Comment by cjmyers** [comment]
Mysterious :-)

**Comment by cjmyers** [comment]
We need to update the tests still, since this will cause changes to HTML.

**Comment by zachzundel** [comment]
I already did. :-)

**Comment by cjmyers** [comment]
Brilliant!  Thanks.

**Pull request merged**
