### PR TITLE
Fix not failing bug

### PR DESCRIPTION
**Pull request by oflatt**

### CODE REVIEW

**Comment by oflatt** [comment]
The irony- one of the test cases failed, and it correctly caught it.
 pIKE_pTAK_cassettes 2.xml Fail 1

**Comment by zachzundel** [comment]
It actually looks like a test suite error, I've submitted a PR there that should hopefully help clean it up.

**Comment by oflatt** [comment]
This pull request should not be merged in, but will sit until the Meher test suite does not fail any more. At that point, I'll merge the changes in a new pull.

**Comment by cjmyers** [comment]
I removed what I thought was the problematic case, but now they are all failing.  Any idea why?

**Comment by zachzundel** [comment]
I thought @oflatt said not to merge this in?

**Comment by cjmyers** [comment]
He said not to merge it until it is fixed.  I just fixed it.

This was how I found the submit bug actually, so I definitely want this done regularly now.

**Pull request merged**
