### PR TITLE
Change to use mkdirp rather than mkdirp-promise

### PR DESCRIPTION
**Pull request by cjmyers**
Fixes issues with adding attachments

### CODE REVIEW

**Comment by danielfang97** [comment]
When is this bug supposed to happen? I tested it, and it appears to be working.

**Comment by cjmyers** [comment]
This was happening when I tried to add any attachments from source.  I think it may be related to the attachment bugs you were experiencing in SBH2.  Basically, mkdirp-promise is broken so changed to mkdirp package.

**Comment by danielfang97** [comment]
What do you mean from source? Is this just doing add attachment on each part page?

**Comment by cjmyers** [comment]
I recall that you were having problems with adding attachments when running from source though working in Docker.  I believe this will fix that issue.  We were using a package that is no longer supported and broken.  To test, you can try to add an attachment using the master branch.  It likely will fail.  However, when run with this branch, it should work.

**Review by danielfang97 — APPROVED** [review]
That test worked. It failed on master, but worked on this branch. Approved

**Pull request merged**
