### PR TITLE
Add COMBINE download functionality

### PR DESCRIPTION
**Pull request by zachzundel**
Allows for download of COMBINE archives with attachments

### CODE REVIEW

**Comment by zachzundel** [comment]
The Travis failure can be ignored, it is due to this coming from a pre-Travis branch. I could rebase but that's a pain and a half.

**Comment by cjmyers** [comment]
Is this branch far from master?

**Comment by cjmyers** [comment]
Please rebase, since it seems you are too far from master.  I cannot build since it seems to be using old libSBOLj prototype for changeURIPrefixVersion.

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 49.550 s
[INFO] Finished at: 2018-02-21T11:36:52+01:00
[INFO] Final Memory: 26M/157M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project SynBioHub: Compilation failure: Compilation failure:
[ERROR] /Users/myers/git/synbiohub/java/src/main/java/org/synbiohub/CloneSubmissionJob.java:[80,26] no suitable method found for changeURIPrefixVersion(java.lang.String,java.lang.String)
[ERROR] method org.sbolstandard.core2.SBOLDocument.changeURIPrefixVersion(java.util.List<org.sbolstandard.core2.Annotation>,java.lang.String,java.lang.String,java.lang.String) is not applicable
[ERROR] (actual and formal argument lists differ in length)
[ERROR] method org.sbolstandard.core2.SBOLDocument.changeURIPrefixVersion(org.sbolstandard.core2.Identified,java.lang.String,java.lang.String,java.lang.String) is not applicable
[ERROR] (actual and formal argument lists differ in length)
[ERROR] method org.sbolstandard.core2.SBOLDocument.changeURIPrefixVersion(java.lang.String,java.lang.String,java.lang.String) is not applicable
[ERROR] (actual and formal argument lists differ in length)
[ERROR] /Users/myers/git/synbiohub/java/src/main/java/org/synbiohub/PrepareSubmissionJob.java:[251,64] no suitable method found for changeURIPrefixVersion(java.lang.String,<nulltype>)
[ERROR] method org.sbolstandard.core2.SBOLDocument.changeURIPrefixVersion(java.util.List<org.sbolstandard.core2.Annotation>,java.lang.String,java.lang.String,java.lang.String) is not applicable
[ERROR] (actual and formal argument lists differ in length)
[ERROR] method org.sbolstandard.core2.SBOLDocument.changeURIPrefixVersion(org.sbolstandard.core2.Identified,java.lang.String,java.lang.String,java.lang.String) is not applicable
[ERROR] (actual and formal argument lists differ in length)
[ERROR] method org.sbolstandard.core2.SBOLDocument.changeURIPrefixVersion(java.lang.String,java.lang.String,java.lang.String) is not applicable
[ERROR] (actual and formal argument lists differ in length)
[ERROR] /Users/myers/git/synbiohub/java/src/main/java/org/synbiohub/PrepareSubmissionJob.java:[253,64] no suitable method found for changeURIPrefixVersion(java.lang.String,java.lang.String)
[ERROR] method org.sbolstandard.core2.SBOLDocument.changeURIPrefixVersion(java.util.List<org.sbolstandard.core2.Annotation>,java.lang.String,java.lang.String,java.lang.String) is not applicable
[ERROR] (actual and formal argument lists differ in length)
[ERROR] method org.sbolstandard.core2.SBOLDocument.changeURIPrefixVersion(org.sbolstandard.core2.Identified,java.lang.String,java.lang.String,java.lang.String) is not applicable
[ERROR] (actual and formal argument lists differ in length)
[ERROR] method org.sbolstandard.core2.SBOLDocument.changeURIPrefixVersion(java.lang.String,java.lang.String,java.lang.String) is not applicable
[ERROR] (actual and formal argument lists differ in length)
[ERROR] /Users/myers/git/synbiohub/java/src/main/java/org/synbiohub/PrepareSnapshotJob.java:[63,18] no suitable method found for changeURIPrefixVersion(java.lang.String,java.lang.String)
[ERROR] method org.sbolstandard.core2.SBOLDocument.changeURIPrefixVersion(java.util.List<org.sbolstandard.core2.Annotation>,java.lang.String,java.lang.String,java.lang.String) is not applicable
[ERROR] (actual and formal argument lists differ in length)
[ERROR] method org.sbolstandard.core2.SBOLDocument.changeURIPrefixVersion(org.sbolstandard.core2.Identified,java.lang.String,java.lang.String,java.lang.String) is not applicable
[ERROR] (actual and formal argument lists differ in length)
[ERROR] method org.sbolstandard.core2.SBOLDocument.changeURIPrefixVersion(java.lang.String,java.lang.String,java.lang.String) is not applicable
[ERROR] (actual and formal argument lists differ in length)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[myers@jiaqi java]$

**Comment by zachzundel** [comment]
Okay, I've rebased this branch onto master.

**Comment by zachzundel** [comment]
BioJava was not actually being used, so I've removed it as a dependency.

**Pull request merged**
