### PR TITLE
tests endpoint publiccollection_copyfromremote

### PR DESCRIPTION
**Pull request by jvscholz**
tests endpoint publiccollection_copyfromremote

### CODE REVIEW

**Comment by cjmyers** [comment]
There is a conflict that I'm not sure how to resolve.

**Comment by cjmyers** [comment]
Seems you might have a copy and paste error

**Comment by jvscholz** [comment]
Updated

**Comment by cjmyers** [comment]
Not really going to do much, since you have no remotes, but okay.

**Pull request merged**
