### PR TITLE
tests endpoint advancedSearch

### PR DESCRIPTION
**Pull request by jvscholz**
tests endpoint advancedSearch

### CODE REVIEW

**Comment by cjmyers** [comment]
Says you have conflicts with tests/test_logout.py.

Also, why do I see the test but no test results being checked in.

**Comment by jvscholz** [comment]
Sorry, this is just a test pull. I should have commented that. For some reason when I resetgetrequests the reset doesn't get made, but when I run tests/test.sh it passes, so I was seeing if the tests would fail if run on travis

**Comment by cjmyers** [comment]
Ah, I see.

**Comment by cjmyers** [comment]
Is this one obsolete?

**Comment by jvscholz** [comment]
Yes, this one is obsolete

**Pull request closed without merging**
